#!/usr/bin/env bash

main() {
  build
}

build() {
  babel --presets es2015 src/lodash-guten.js > lodash-guten.js
  sed -i 's/})(undefined,/})(this,/' lodash-guten.js
  #rollup -c
  :
}

release() {
  build
  sed -i "s/\"version\":.*/\"version\": \"$1\",/" bower.json package.json
  cp lodash-guten.js bower.json package.json dist

  cd dist
  # npm release
  npm publish

  # bower release
  git add .
  git commit -m "$1"
  git tag "$1"
  git push --tags
}


case "$1" in
  "" ) main ;;
  build | b ) build ;;
  release | r ) shift; release "$@" ;;
esac
